ft/contact-page
IGIRANEZAJosue/website-project pull request #14
Opened 2024-06-04 16:45 UTC by IGIRANEZAJosue

**Implementation of the contact page**

2024-06-04 17:53 UTC, IGIRANEZAJosue commented
![](https://github.trello.services/images/mini-trello-icon.png) [Imprint page - Desktop](https://trello.com/c/DKvH5Jl5/31-imprint-page-desktop)

2024-06-04 18:00 UTC, musi922 commented
There is no image in the navbar maybe you can fix that

2024-06-05 08:07 UTC, IGIRANEZAJosue commented
![](https://github.trello.services/images/mini-trello-icon.png) [Imprint page - Responsiveness](https://trello.com/c/63yw2Mw4/32-imprint-page-responsiveness)

2024-06-05 10:27 UTC, uwumukiza123 commented on contact.html
> +      <!-- Navbar -->
Remember to remove comments

2024-06-05 10:30 UTC, uwumukiza123 commented on contact.html
> +            <div class="flex flex-col md:text-2xl lg:text-2xl">
I think, this md:text-2xl will also work on the larger screen, you don't need to add another one

2024-06-05 10:32 UTC, uwumukiza123 commented on contact.html
> +            class="top-0 z-10 sticky flex flex-row justify-between items-center lg:mb-12 md:px-8 p-4 lg:p-6 xl:p-6 font-outfit"
Also here this lg:p-6 will also work on the xl screens, you don't need to add

2024-06-05 10:36 UTC, uwumukiza123 commented on contact.html
> +               class="absolute lg:flex flex-col lg:items-end space-y-10 md:space-y-24 lg:space-y-0 hidden md:ml-[20%] lg:ml-0 pt-[120%] md:pt-[70%] lg:pt-14 pl-32 lg:pl-[87%] font-bold md:font-bold l
Same as here, font-bold will also work on the md(medium) screens you can remove this md:font-bold

2024-06-05 10:37 UTC, uwumukiza123 commented on contact.html
> +      <!-- container -->
Remove comments

2024-06-05 10:37 UTC, uwumukiza123 commented on contact.html
> +               class="absolute lg:flex flex-col lg:items-end space-y-10 md:space-y-24 lg:space-y-0 hidden md:ml-[20%] lg:ml-0 pt-[120%] md:pt-[70%] lg:pt-14 pl-32 lg:pl-[87%] font-bold md:font-bold l
Same as here, font-bold will also work on the md(medium) screens you can remove this md:font-bold

2024-06-05 10:39 UTC, uwumukiza123 commented on contact.html
> +      <!-- Red image -->
Same as here, you can delete the comments

2024-06-05 10:40 UTC, uwumukiza123 commented on contact.html
> +      <!-- Footer -->
Same as here

2024-06-05 10:44 UTC, uwumukiza123 approved these changes

2024-06-05 10:44 UTC, uwumukiza123 commented on src/sections/Navbar.html
> +   <div class="flex flex-col md:text-2xl lg:text-2xl">
This md:text-2xl will also work on larger screens, you can remove this lg:text-2xl

2024-06-05 10:51 UTC, uwumukiza123 commented on src/sections/Navbar.html
> +   class="top-0 z-10 sticky flex flex-row justify-between items-center lg:mb-12 md:px-8 p-4 lg:p-6 xl:p-6 font-outfit"
Same as here, this lg:p-6 will also work on the xl screens

2024-06-05 10:55 UTC, uwumukiza123 commented on src/sections/Navbar.html
> +      class="absolute lg:flex flex-col lg:items-end space-y-10 md:space-y-24 lg:space-y-0 hidden md:ml-[20%] lg:ml-0 pt-[120%] md:pt-[70%] lg:pt-14 pl-32 lg:pl-[87%] font-bold md:font-bold lg:font-no
Here as well font-bold will also work on medium screens

2024-06-05 11:02 UTC, uwumukiza123 requested changes
You did a great job, but there are some minor changes

2024-06-05 15:24 UTC, uwumukiza123 approved these changes

2024-06-05 18:34 UTC, Algor-Fernand approved these changes
This looks fine to me. Good job 🎉🎉

2024-06-05 18:34 UTC, merged