Ft navbar
IGIRANEZAJosue/website-project pull request #3
Opened 2024-05-28 13:55 UTC by nsengaqueen

feat: implementation of the navbar section and it's responsiveness

2024-05-28 15:55 UTC, IGIRANEZAJosue commented on src/sections/Header.html
> +  />
The navbar is not responsive on the desktop breakpoint.
Try using flex alignments instead of paddings and margins.

2024-05-28 16:05 UTC, nsengaqueen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar - Responsiveness](https://trello.com/c/tVe2snCg/10-navbar-responsiveness)

2024-05-28 16:48 UTC, nsengaqueen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar - Desktop](https://trello.com/c/Vu03csSg/9-navbar-desktop)

2024-05-29 15:01 UTC, Algor-Fernand commented on Images/Background Phone screen.svg
Look into the naming of the files.

2024-05-29 15:01 UTC, Algor-Fernand requested changes
I have left some that you need to work on. But good job.

2024-05-30 10:37 UTC, closed without merging