feat: Ft/navbar
IGIRANEZAJosue/website-project pull request #5
Opened 2024-05-30 10:45 UTC by nsengaqueen

[x] Renaming the branch from ft-navbar to ft/navbar
[x] Deleted the unnecessary files in our branch (Hero, Contact, About, Services)
[x] Renamed the Header file name to Navbar 
[x] Reducing the non-arbitrary values where possible

2024-05-30 12:58 UTC, IGIRANEZAJosue commented on src/sections/Navbar.html
> +   <div class="flex flex-col text-[1rem] md:text-2xl lg:text-2xl">
You can remove the 1rem arbitrary value; It doesn't change anything since the text is already 16px by default.

2024-05-31 13:44 UTC, christellealexia commented
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar - Responsiveness](https://trello.com/c/tVe2snCg/10-navbar-responsiveness)

2024-05-31 14:26 UTC, IGIRANEZAJosue commented on src/sections/Navbar.html
> +  </div>
The text for the navbar elements should be bigger and bolder and the gap should be bigger too.

2024-06-03 14:28 UTC, Algor-Fernand commented on Images/Group 4.png
The naming here isn't consistent with how we named our files, the extension as well.

2024-06-03 14:29 UTC, Algor-Fernand commented on package.json
> +    "prettier": "^3.2.5",
what's this package for? is it really necessary.

2024-06-03 14:29 UTC, Algor-Fernand commented on src/sections/Navbar.html
> +  class="flex flex-row justify-between items-center md:px-8 p-4 lg:p-6 xl:p-6 font-outfit  lg:mb-12"
I think there's too much space before the last utility class.

2024-06-03 14:33 UTC, Algor-Fernand commented on .prettierr.js
What is this file for?

2024-06-03 14:34 UTC, Algor-Fernand requested changes
The deployment looks good but there are a couple of things I have mentioned that should be changed.

2024-06-03 16:39 UTC, Algor-Fernand approved these changes

2024-06-03 16:39 UTC, merged