Ft/references
IGIRANEZAJosue/website-project pull request #7
Opened 2024-05-31 15:54 UTC by nsengaqueen

In this PR we added the following :

We created a new reference branch
 Deleted the unnecessary files in our branch (Hero, Contact, About, Services)
 Made the page responsive
 Reducing the non-arbitrary values where possible

2024-06-03 16:13 UTC, Algor-Fernand commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
I am not sure if we need this in our project.

2024-06-03 16:15 UTC, Algor-Fernand commented on src/sections/References.html
> +<section class="flex flex-col items-end gap-0 pt-20 pb-20 pl-2 pr-16 text-2xl md:gap-3 lg:gap-3 bg-customYellow md:p-32 lg:p-20 rounded-b-md font-outfit gap pt">
I think if padding top and padding bottom have the same padding you can change into a single class: 'py'.

2024-06-03 16:20 UTC, Algor-Fernand commented on tailwind.config.js
> +        '.clip-bottom': {
I love this 🤩🤩🤩

2024-06-04 13:48 UTC, uwumukiza123 requested changes

2024-06-04 13:48 UTC, uwumukiza123 commented on .vscode/settings.json
Are you using this Json file? If not you can remove it since is empty

2024-06-04 13:48 UTC, uwumukiza123 commented on src/sections/References.html
For this references It's better to put them in one array for better performance and fewer lines of code

2024-06-05 13:33 UTC, Algor-Fernand approved these changes

2024-06-05 13:34 UTC, merged